id: ID93F9639
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T20:24:35+00:00'
last_modified: '2022-06-07T21:44:10.693318+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23770
  title: རྒྱལ་རབས་གསལ་བའི་མེ་ལོང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9A66:
      image_group_id: I2645
      title: ''
      total_pages: 530
      order: 1
      base_file: 9A66.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
