id: P004291
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W23770
  title: རྒྱལ་རབས་གསལ་བའི་མེ་ལོང
  author: ''
  volumes:
    501a6346c996483cbc71aaffdae1d5f0:
      image_group_id: I2645
      title: ''
      volume_number: 1
      total_pages: 530
      base_file: v001.txt
