id: P004291
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:08:06.906533
source_metadata:
  id: bdr:W23770
  title: རྒྱལ་རབས་གསལ་བའི་མེ་ལོང
  author: ''
  volumes:
    501a6346c996483cbc71aaffdae1d5f0:
      image_group_id: I2645
      title: ''
      volume_number: 1
      total_pages: 530
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
